// Generated by scripts/generate_subtitle_font_catalog.py. Do not edit.
export const GENERATED_SUBTITLE_FONT_FILES: Array<{ family: string; file: string }> = [
  {
    "family": "Aoboshi One",
    "file": "aoboshi-one.ttf"
  },
  {
    "family": "Black And White Picture",
    "file": "black-and-white-picture.ttf"
  },
  {
    "family": "Bpmf Zihi Kai Std",
    "file": "bpmf-zihi-kai-std.ttf"
  },
  {
    "family": "Cherry Bomb One",
    "file": "cherry-bomb-one.ttf"
  },
  {
    "family": "Chokokutai",
    "file": "chokokutai.ttf"
  },
  {
    "family": "Darumadrop One",
    "file": "darumadrop-one.ttf"
  },
  {
    "family": "Diphylleia",
    "file": "diphylleia.ttf"
  },
  {
    "family": "Do Hyeon",
    "file": "do-hyeon.ttf"
  },
  {
    "family": "Gamja Flower",
    "file": "gamja-flower.ttf"
  },
  {
    "family": "Gasoek One",
    "file": "gasoek-one.ttf"
  },
  {
    "family": "Grandiflora One",
    "file": "grandiflora-one.ttf"
  },
  {
    "family": "Gugi",
    "file": "gugi.ttf"
  },
  {
    "family": "Hahmlet",
    "file": "hahmlet.ttf"
  },
  {
    "family": "Hi Melody",
    "file": "hi-melody.ttf"
  },
  {
    "family": "Kaisei Decol",
    "file": "kaisei-decol.ttf"
  },
  {
    "family": "Kaisei HarunoUmi",
    "file": "kaisei-harunoumi.ttf"
  },
  {
    "family": "Kaisei Opti",
    "file": "kaisei-opti.ttf"
  },
  {
    "family": "Kaisei Tokumin",
    "file": "kaisei-tokumin.ttf"
  },
  {
    "family": "Kapakana",
    "file": "kapakana.ttf"
  },
  {
    "family": "Kirang Haerang",
    "file": "kirang-haerang.ttf"
  },
  {
    "family": "Klee One",
    "file": "klee-one.ttf"
  },
  {
    "family": "LINE Seed JP",
    "file": "line-seed-jp.ttf"
  },
  {
    "family": "Mochiy Pop One",
    "file": "mochiy-pop-one.ttf"
  },
  {
    "family": "Mochiy Pop P One",
    "file": "mochiy-pop-p-one.ttf"
  },
  {
    "family": "Moirai One",
    "file": "moirai-one.ttf"
  },
  {
    "family": "Orbit",
    "file": "orbit.ttf"
  },
  {
    "family": "Palette Mosaic",
    "file": "palette-mosaic.ttf"
  },
  {
    "family": "Potta One",
    "file": "potta-one.ttf"
  },
  {
    "family": "Rampart One",
    "file": "rampart-one.ttf"
  },
  {
    "family": "Reggae One",
    "file": "reggae-one.ttf"
  },
  {
    "family": "Rock 3D",
    "file": "rock-3d.ttf"
  },
  {
    "family": "RocknRoll One",
    "file": "rocknroll-one.ttf"
  },
  {
    "family": "Shippori Antique",
    "file": "shippori-antique.ttf"
  },
  {
    "family": "Shippori Antique B1",
    "file": "shippori-antique-b1.ttf"
  },
  {
    "family": "Single Day",
    "file": "single-day.ttf"
  },
  {
    "family": "Slackside One",
    "file": "slackside-one.ttf"
  },
  {
    "family": "Stick",
    "file": "stick.ttf"
  },
  {
    "family": "Stylish",
    "file": "stylish.ttf"
  },
  {
    "family": "Sunflower",
    "file": "sunflower.ttf"
  },
  {
    "family": "Train One",
    "file": "train-one.ttf"
  },
  {
    "family": "UoqMunThenKhung",
    "file": "uoqmunthenkhung.ttf"
  },
  {
    "family": "WDXL Lubrifont JP N",
    "file": "wdxl-lubrifont-jp-n.ttf"
  },
  {
    "family": "WDXL Lubrifont SC",
    "file": "wdxl-lubrifont-sc.ttf"
  },
  {
    "family": "WDXL Lubrifont TC",
    "file": "wdxl-lubrifont-tc.ttf"
  },
  {
    "family": "Yusei Magic",
    "file": "yusei-magic.ttf"
  },
  {
    "family": "ZCOOL KuaiLe",
    "file": "zcool-kuaile.ttf"
  },
  {
    "family": "ZCOOL QingKe HuangYou",
    "file": "zcool-qingke-huangyou.ttf"
  },
  {
    "family": "ZCOOL XiaoWei",
    "file": "zcool-xiaowei.ttf"
  },
  {
    "family": "Zen Antique",
    "file": "zen-antique.ttf"
  },
  {
    "family": "Zen Antique Soft",
    "file": "zen-antique-soft.ttf"
  },
  {
    "family": "Zen Kurenaido",
    "file": "zen-kurenaido.ttf"
  },
  {
    "family": "Pop Gothic",
    "file": "pop-gothic.ttf"
  },
  {
    "family": "Bpmf Iansui",
    "file": "bpmf-iansui.ttf"
  },
  {
    "family": "Dokdo",
    "file": "dokdo.ttf"
  },
  {
    "family": "East Sea Dokdo",
    "file": "east-sea-dokdo.ttf"
  },
  {
    "family": "Gaegu",
    "file": "gaegu.ttf"
  },
  {
    "family": "Iansui",
    "file": "iansui.ttf"
  },
  {
    "family": "Liu Jian Mao Cao",
    "file": "liu-jian-mao-cao.ttf"
  },
  {
    "family": "Long Cang",
    "file": "long-cang.ttf"
  },
  {
    "family": "LXGW Marker Gothic",
    "file": "lxgw-marker-gothic.ttf"
  },
  {
    "family": "LXGW WenKai TC",
    "file": "lxgw-wenkai-tc.ttf"
  },
  {
    "family": "Ma Shan Zheng",
    "file": "ma-shan-zheng.ttf"
  },
  {
    "family": "Nanum Brush Script",
    "file": "nanum-brush-script.ttf"
  },
  {
    "family": "Nanum Pen Script",
    "file": "nanum-pen-script.ttf"
  },
  {
    "family": "New Tegomin",
    "file": "new-tegomin.ttf"
  },
  {
    "family": "Poor Story",
    "file": "poor-story.ttf"
  },
  {
    "family": "Shizuru",
    "file": "shizuru.ttf"
  },
  {
    "family": "Yomogi",
    "file": "yomogi.ttf"
  },
  {
    "family": "Yuji Boku",
    "file": "yuji-boku.ttf"
  },
  {
    "family": "Yuji Hentaigana Akari",
    "file": "yuji-hentaigana-akari.ttf"
  },
  {
    "family": "Yuji Hentaigana Akebono",
    "file": "yuji-hentaigana-akebono.ttf"
  },
  {
    "family": "Yuji Mai",
    "file": "yuji-mai.ttf"
  },
  {
    "family": "Yuji Syuku",
    "file": "yuji-syuku.ttf"
  },
  {
    "family": "Zhi Mang Xing",
    "file": "zhi-mang-xing.ttf"
  },
  {
    "family": "NaikaiFont",
    "file": "naikaifont.ttf"
  },
  {
    "family": "LXGW WenKai Mono TC",
    "file": "lxgw-wenkai-mono-tc.ttf"
  },
  {
    "family": "M PLUS 1 Code",
    "file": "m-plus-1-code.ttf"
  },
  {
    "family": "Monomaniac One",
    "file": "monomaniac-one.ttf"
  },
  {
    "family": "Nanum Gothic Coding",
    "file": "nanum-gothic-coding.ttf"
  },
  {
    "family": "Bagel Fat One",
    "file": "bagel-fat-one.ttf"
  },
  {
    "family": "Bpmf Huninn",
    "file": "bpmf-huninn.ttf"
  },
  {
    "family": "Chiron GoRound TC",
    "file": "chiron-goround-tc.ttf"
  },
  {
    "family": "Cute Font",
    "file": "cute-font.ttf"
  },
  {
    "family": "Dongle",
    "file": "dongle.ttf"
  },
  {
    "family": "Hachi Maru Pop",
    "file": "hachi-maru-pop.ttf"
  },
  {
    "family": "Huninn",
    "file": "huninn.ttf"
  },
  {
    "family": "Jua",
    "file": "jua.ttf"
  },
  {
    "family": "Kiwi Maru",
    "file": "kiwi-maru.ttf"
  },
  {
    "family": "Kosugi Maru",
    "file": "kosugi-maru.ttf"
  },
  {
    "family": "M PLUS Rounded 1c",
    "file": "m-plus-rounded-1c.ttf"
  },
  {
    "family": "Tsukimi Rounded",
    "file": "tsukimi-rounded.ttf"
  },
  {
    "family": "Zen Maru Gothic",
    "file": "zen-maru-gothic.ttf"
  },
  {
    "family": "GenSenRounded TW",
    "file": "gensenrounded-tw.otf"
  },
  {
    "family": "Asta Sans",
    "file": "asta-sans.ttf"
  },
  {
    "family": "BIZ UDGothic",
    "file": "biz-udgothic.ttf"
  },
  {
    "family": "BIZ UDPGothic",
    "file": "biz-udpgothic.ttf"
  },
  {
    "family": "Black Han Sans",
    "file": "black-han-sans.ttf"
  },
  {
    "family": "Chiron Hei HK",
    "file": "chiron-hei-hk.ttf"
  },
  {
    "family": "Chocolate Classical Sans",
    "file": "chocolate-classical-sans.ttf"
  },
  {
    "family": "Dela Gothic One",
    "file": "dela-gothic-one.ttf"
  },
  {
    "family": "DotGothic16",
    "file": "dotgothic16.ttf"
  },
  {
    "family": "Gothic A1",
    "file": "gothic-a1.ttf"
  },
  {
    "family": "Gowun Dodum",
    "file": "gowun-dodum.ttf"
  },
  {
    "family": "IBM Plex Sans JP",
    "file": "ibm-plex-sans-jp.ttf"
  },
  {
    "family": "IBM Plex Sans KR",
    "file": "ibm-plex-sans-kr.ttf"
  },
  {
    "family": "Kosugi",
    "file": "kosugi.ttf"
  },
  {
    "family": "M PLUS 1",
    "file": "m-plus-1.ttf"
  },
  {
    "family": "M PLUS 1p",
    "file": "m-plus-1p.ttf"
  },
  {
    "family": "M PLUS 2",
    "file": "m-plus-2.ttf"
  },
  {
    "family": "M PLUS U",
    "file": "m-plus-u.ttf"
  },
  {
    "family": "Murecho",
    "file": "murecho.ttf"
  },
  {
    "family": "Nanum Gothic",
    "file": "nanum-gothic.ttf"
  },
  {
    "family": "Noto Sans HK",
    "file": "noto-sans-hk.ttf"
  },
  {
    "family": "Noto Sans JP",
    "file": "noto-sans-jp.ttf"
  },
  {
    "family": "Noto Sans KR",
    "file": "noto-sans-kr.ttf"
  },
  {
    "family": "Noto Sans SC",
    "file": "noto-sans-sc.ttf"
  },
  {
    "family": "Noto Sans TC",
    "file": "noto-sans-tc.ttf"
  },
  {
    "family": "Sawarabi Gothic",
    "file": "sawarabi-gothic.ttf"
  },
  {
    "family": "Zen Kaku Gothic Antique",
    "file": "zen-kaku-gothic-antique.ttf"
  },
  {
    "family": "Zen Kaku Gothic New",
    "file": "zen-kaku-gothic-new.ttf"
  },
  {
    "family": "BIZ UDMincho",
    "file": "biz-udmincho.ttf"
  },
  {
    "family": "BIZ UDPMincho",
    "file": "biz-udpmincho.ttf"
  },
  {
    "family": "Cactus Classical Serif",
    "file": "cactus-classical-serif.ttf"
  },
  {
    "family": "Chiron Sung HK",
    "file": "chiron-sung-hk.ttf"
  },
  {
    "family": "Gowun Batang",
    "file": "gowun-batang.ttf"
  },
  {
    "family": "Hina Mincho",
    "file": "hina-mincho.ttf"
  },
  {
    "family": "Nanum Myeongjo",
    "file": "nanum-myeongjo.ttf"
  },
  {
    "family": "Noto Serif HK",
    "file": "noto-serif-hk.ttf"
  },
  {
    "family": "Noto Serif JP",
    "file": "noto-serif-jp.ttf"
  },
  {
    "family": "Noto Serif KR",
    "file": "noto-serif-kr.ttf"
  },
  {
    "family": "Noto Serif SC",
    "file": "noto-serif-sc.ttf"
  },
  {
    "family": "Noto Serif TC",
    "file": "noto-serif-tc.ttf"
  },
  {
    "family": "Sawarabi Mincho",
    "file": "sawarabi-mincho.ttf"
  },
  {
    "family": "Shippori Mincho",
    "file": "shippori-mincho.ttf"
  },
  {
    "family": "Shippori Mincho B1",
    "file": "shippori-mincho-b1.ttf"
  },
  {
    "family": "Song Myung",
    "file": "song-myung.ttf"
  },
  {
    "family": "Yeon Sung",
    "file": "yeon-sung.ttf"
  },
  {
    "family": "Zen Old Mincho",
    "file": "zen-old-mincho.ttf"
  }
];


